apiVersion: apps/v1
kind: Deployment
metadata:
  name: awm-api
spec:
  selector:
    matchLabels:
      app: awm-api
  template:
    metadata:
      labels:
        app: awm-api
    spec:
      containers:
        - name: awm-api
          image: hughdo/awm-api:GITHUB_SHA
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1.5Gi"
              cpu: 1
          env:
            - name: DB_NAME
              value: awm_api_production
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: awm-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: awm-db-secret
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: awm-db-secret
                  key: DB_URL
            - name: HOST
              value: awm.hughdo.dev
            - name: HOST_EMAIL
              value: awm@gmail.com
            - name: MAIL_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: awm-mail-secret
                  key: MAIL_USER_NAME
            - name: MAIL_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: awm-mail-secret
                  key: MAIL_USER_PASSWORD
            - name: MAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: awm-mail-secret
                  key: MAIL_ADDRESS
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: awm-mail-secret
                  key: MAIL_PORT
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: awm-mail-secret
                  key: SECRET_KEY
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: awm-mail-secret
                  key: JWT_ALGORITHM
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: awm-db-secret
                  key: SECRET_KEY_BASE
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: awm-api-svc
spec:
  selector:
    app: awm-api
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: awm-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - awm.hughdo.dev
      secretName: awm-api-tls
  rules:
    - host: awm.hughdo.dev
      http:
        paths:
          - path: /api(.*)
            backend:
              serviceName: awm-api-svc
              servicePort: 4000
